# This workflow is to build for kotlin on jdk 17.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
# And also https://github.com/actions/setup-java/tree/v3/
# Should really use JDK 20 but this may not yet be available on github actions
name: Android CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:    
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
#    - uses: actions/upload-artifact@v3
#      with:
#        name: Package
#        path: build/libs
